### ISSUE TITLE
simple_multipass output issue

### ISSUE THREAD

**Issue by akashsngh** [OpenPIV/openpiv-python-examples#15]
Hello,
  When I plotted the output of the simple multipass, the direction of the quivers where not aligned. The exact bug is in the sign of the v component and the y array output of the simple_multipass. The correction is v= -v, and y = y[::-1, :]  i.e. the outer axis of y needs to be inversed.  Also, the u and v outputted are displacements and not velocities, so an additional division by dt should be added in.

Best regards.
Akash

**Comment by alexlib** [comment]
which notebook is it?

**Comment by akashsngh** [comment]
Hello Alex,
  I did not get the question. Should I share the notebook with the example ?@alexlib

Best,
Akash

**Comment by akashsngh** [comment]
Okay, here is the notebook. I have added some part regarding the corrections

https://colab.research.google.com/drive/1f3lSGfhQKPhnWECnzm1LrkvVRjDRZSRh?usp=sharing

**Comment by akashsngh** [comment]
Hello Alex,
  Yes, that is true I am inverting the y-axis to bring the 0,0 at the bottom left.  However, when plotting, this should work or both the image and the quiver array, so even if I comment on this line (#fig.gca().invert_yaxis()), the results seem wrong. 
  
  However, the x, y output I have from pyprocess.get_coordinates ( I use it to plot the results of pyprocess.extended_search_area_piv), are rightly shaped so I do not need to reshape the y. 
  
  Maybe it is a convention thing, I hope I am clear. Thanks!

**Comment by alexlib** [comment]
we shall be correct in the output matrix, x,y,u,v shall be correct,
independent of how we present those. v is negative and that's what we have
in the file I think. The way to show it shall be adjusted depending on the
way you need it - with or without the image, with the origin at the lower
left or upper left. all these options are possible.
